.PHONY: clean All

All:
	@echo "----------Building project:[ Pointers_Section_Challenge - Debug ]----------"
	@cd "Pointers_Section_Challenge" && "$(MAKE)" -f  "Pointers_Section_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Pointers_Section_Challenge - Debug ]----------"
	@cd "Pointers_Section_Challenge" && "$(MAKE)" -f  "Pointers_Section_Challenge.mk" clean
